language: groovy

install:
  # Secrets (including encrypted PGP key) are not available in PR - skip release configuration to do not fail build
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      # There is problem with aborting build on command in if failure - http://steven.casagrande.io/articles/travis-ci-and-if-statements/
      openssl aes-256-cbc -K $encrypted_5393bb1c9f2d_key -iv $encrypted_5393bb1c9f2d_iv -in gradle/gpg-key.asc.enc -d | gpg --fast-import || travis_terminate 1
      export GRADLE_OPTS='-Dorg.gradle.project.signing.keyId=0694F057 -Dorg.gradle.project.signing.secretKeyRingFile=$HOME/.gnupg/secring.gpg -Dorg.gradle.project.signing.password= -Dorg.gradle.project.gradle.publish.key=$PLUGIN_PORTAL_API_KEY -Dorg.gradle.project.gradle.publish.secret=$PLUGIN_PORTAL_API_SECRET'
    fi;
  - "export TRAVIS_COMMIT_MSG=$(git log --format=%B -n 1 $TRAVIS_COMMIT)"
  - git config user.email "szpak-ci@users.noreply.github.com"
  - git config user.name "Szpak CI Bot"
  # Chandler for release notes synchronization
  - ruby --version
  - rvm install 2.4.1
  - ruby --version
  - gem install --no-document chandler -v 0.7.0

script:
  - ./gradlew prepareForCiBuild -s -i -Prelease.disableChecks && ./gradlew ciBuild -s -i -Prelease.disableChecks -PchangelogSync

#env:
#  global:
#  - secure: TODO
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk11
      env: SKIP_RELEASE=true
    - jdk: openjdk15
      env: SKIP_RELEASE=true
